### provide_fees#index
GET  http://localhost:3000/api/provide_feeds

### provide_fees#show
GET  http://localhost:3000/api/provide_feeds/3

### provide_fees#create
POST http://localhost:3000/api/provide_feeds
content-type: application/json

{
  "feed": {
    "url": "http://qiita.com/search?q=python",
    "node_type": "XPATH",
    "node": "//h1[@class='searchResult_itemTitle']"
  }
}

### provide_feeds#destroy
DELETE  http://localhost:3000/api/provide_feeds/3

### user authentication
POST http://localhost:3000/api/sign_in/
content-type: application/json

{
  "email": "hoge@gmail.com",
  "password": "hogehoge"
}
